name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # или укажите нужную ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Установка Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Установка зависимостей
        run: npm install

      - name: Сборка проекта Gulp
        run: npx gulp build # Убедитесь, что эта команда собирает проект в папку build

      - name: Деплой на GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
